name: Dan Healy Music
favicon: null
layout_spectrum: 0.37351890560239553
typography_spectrum: 0.19168832688592374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6893846888560802
  lightness: 0.03627256001345813
  saturation: 0.9565219080541283
  rhythmicContrast: 0.36212505120784044
purpose: []
